config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  #[:alnum:] - алфавитные и числовые символы всех языков мира(в нашем случае вместо а-яА-яa-zA-z0-9)
  REGEXP = /#[[:alnum:]_]+/

  has_many :hashtag_questions
  #имеет много вопросов сквозь хештегивопросы
  has_many :questions, through: :hashtag_questions

  validates :name, uniqueness: true
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question

  validates :question_id, uniqueness: {scope: :hashtag_id}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :hashtag_questions
  has_many :hashtags, through: :hashtag_questions

  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }

  before_save :set_hashtags

  private

  def set_hashtags
    hashtag_questions.delete_all
    (text + ' ' + answer.to_s).scan(Hashtag::REGEXP).uniq.each do |hashtag|
      #hashtag[1..-1] - с второго символа до конца слова
      hashtags << Hashtag.find_or_create_by(name: hashtag[1..-1])
    end
  end
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  #парамерты работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions, dependent: :destroy

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :username, format: {with: /\A\w{5,40}\z/,
    message: "Можно использовать только латинские буквы, цифры от 5 до 40 символов и знак подчеркивания '_'"}
  validates :header_color, format: {with: /#[a-fA-F0-9]{6}/,
    message: "Ах ты жук, нельзя лОмать мне сайт:)"}
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-zа-я]{2,})\z/i

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password
  before_validation { |user| user.username = user.username.downcase }

  def encrypt_password
    if self.password.present?
    #создаем т.н. "соль" - рандомная строка усложняющая задачу хакерам
    self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

    #создаем хэш пароля - длинная уникальная строка, из которой невозможно восстановить
    #исходный пароль
    self.password_hash = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  #служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email) # сперва находим кандидата на email

    # обратите внимание: сравнивается password_hash, а оригинальный пароль так никогда
    # и не сохраняется нигде
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params.require(:id))
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user
    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален!'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    current_user.present? ? true : verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_count = @questions.count
    @answer_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answer_count
  end

  def destroy
    if @user.destroy
      redirect_to root_url, notice: 'Вы удалили свой аккаунт'
    else
      redirect_to user_path(@user)
    end
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def load_questions
    @questions = @user.questions.includes(:hashtags).order(created_at: :desc)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :header_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sklonenie(number, krokodil, krokodila, krokodilov)
    if number == nil || !number.is_a?(Numeric)
      number = 0
    end

    ostatok = number % 100

    if ostatok >= 11 && ostatok <= 14
      return krokodilov
    end

    ostatok = number % 10

    if ostatok == 1
      return krokodil
    end
    if ostatok >= 2 && ostatok <= 4
      return krokodila
    end
    if (ostatok >= 5 && ostatok <= 9) || ostatok == 0
      return krokodilov
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def question_hashtags(question)
    question.hashtags.map do |hashtag|
      link_to("##{hashtag.name}", hashtag_path(hashtag))
    end.join(' ').html_safe
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    user.avatar_url.present? ? user.avatar_url : asset_path('avatar.jpg')
  end

  def user_name(user)
    user.name.present? ? user.name :
      content_tag('span', '', class: "fa fa-user-secret", title: "не указано имя")
  end
end

app/views/hashtags/show.html.erb
<div class="user-questions buffer-both">
  <div class="questions-list">
    <div class="number-of-questions">
    <% @hashtag.questions.each do |question| %>
      <%= render partial: 'questions/question', object: question %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Хорошие вопросы</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <script type="text/javascript" src="colorpicker.min.js"></script>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="header">
    <div class="container">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to "хорошие вопросы", root_path %></h1>
      </div>

      <div class="header-nav">
        <% if current_user %>
          <%= link_to "@#{current_user.username}", user_path(current_user) %>
          <%= link_to 'Выйти', session_path, data: {method: :delete} %>
        <% else %>
          <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
          <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container">
      <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
            <%= content_tag :div, message, class: "flash-#{name}" %>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags hl: 'ru' unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="hashtag buffer-bottom10">
      <%= question_hashtags(question) %>
    </div>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
      <% if question.author %>
        Вопрос от: <%= link_to User.find_by(id: question.author_id).username,
          user_path(User.find_by(id: question.author_id)) %>
      <% else %>
        Вопрос от: Неизвестного пользователя
      <% end %>
    </div>
  </div>

  <% if question.user == current_user %>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
        method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="title-small">
    <%= link_to 'Удалить профиль', user_path(@user),  :method => :delete,  data: { confirm: 'Действительно удалить?' }  if current_user == @user %>
  </div>

  <div class="column-1-2">
    <div class="form">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-filed">
          <%= f.label :username, 'Никнейм', class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :name, 'Имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label 'URL вашей аватарки', class: 'form-label' %>
          <%= f.text_field :avatar_url, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'Цвет фона', class: 'form-label' %>
          <%= f.color_field :header_color, value: "#005a55", class: 'form-color-field' %>
        </div>

        <div class="buffer-top-large buffer-bottom">
          Если не хотите менять пароль - оставьте эти поля пустыми!
        </div>

        <div class="form-filed">
          <%= f.label :password, 'Пароль', class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%= f.submit 'Сохранить', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
      <%= user_name(user) %>
    </div>
  <% end %>
</div>

<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h2 class="title-medium">Наши хештеги</h2>
  </div>

  <% @hashtags.each do |hashtag| %>
    <%= link_to "##{hashtag.name}", hashtag_path(hashtag) %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоеденятесь к нам!</h1>

  <div class="column-1-2">
    <div class="form">
      <%= form_for @user do |f| %>

        <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-field">
          <%= f.label :email, 'Email', class: 'form-label' %>
          <%= f.text_field :email, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :username, 'Никнейм', class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :name, 'Имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'Цвет фона', class: 'form-label' %>
          <%= f.color_field :header_color, value: "#005a55", class: 'form-color-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :password, 'Пароль', class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-filed">
          <%= f.label :password_confirmation, 'Пароль еще раз', class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= @user.header_color %>;">
  <h1 class="title-medium"><%= @user.name %></h1>
  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">@<%= @user.username %></h2>
  <div class="user-detalies">
    <div class="user-ask-button container text-center">
      <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
    </div>

    <div class="user-statistics container text-center">
      <div class="column-1-3">
        <h1 class="title-small"><%= @questions_count %></h1>
        <p><%= sklonenie(@questions_count, 'вопрос', 'вопроса', 'вопросов') %></p>
      </div>

      <div class="column-1-3">
        <h1 class="title-small"><%= @answer_count %></h1>
        <p><%= sklonenie(@answer_count, 'ответ', 'ответа', 'ответов') %></p>
      </div>

      <div class="column-1-3">
        <h1 class="title-small"><%= @unanswered_count %></h1>
        <p><%= sklonenie(@unanswered_count  , 'безответный', 'безответных', 'безответных') %></p>
      </div>
    </div>
  </div>
</div>

<div class="user-question-form-div column1-4 column1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags hl: 'ru' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <div class="number-of-questions">
        Всего <%= @questions_count %>
        <%= sklonenie(@questions_count, 'вопрос', 'вопроса', 'вопросов') %>:
      </div>
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>